### ISSUE TITLE
Nie dobry nazov triedy. 

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Vypis_adresara#1]
FileNotExists to je anglictina ako z Winnetoua. :) "Winnetou ist pueblo, zjest vela bizon a odpocinut" 

Vhodnejsie nazvy
FileDoesNotExistException (toto je opravena verzia tvojho nazvu)
NoFileException (skratena verzia)
FileNotFoundException (tato Exception uz existuje a nazov je najviac vhodny pre to, co chces urobit). Ak potrebujes vypisat nieco na stderr, tak si od nej odded triedu a v konstruktore vypis na stderr. V podstate to aj tak mas, len dedis od Exception.

Neda sa takyto komentar dat k suboru class, tak tuto poznamku dam sem. Do repozitara nepatria skompilovane subory. Repozitare sluzia iba na ukladanie zdrojovych suborov, pripadne roznych projektovych zdrojov, ako obrazkov, videi a pod.

https://github.com/mhanis2/Vypis_adresara/blob/a2b921612bfd7759a67950fc6f74ffee6679c876/src/sk/maha/vypis/exceptions/FileNotExistsException.java#L3

**Comment by mhanis2** [comment]
Exception FileNotExistsException som odstranil a nahradil som ju FileNotFoundException.
