### ISSUE TITLE
v nazve jednotky (disku) musi byt velke pismeno?

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Vypis_adresara#2]
to je podla mna nespravne, spravne by mal program brat akekolvek pismeno (aj velke, aj male), kedze cesty (aspon vo Windows) su case insensitive. 

https://github.com/mhanis2/Vypis_adresara/blob/a2b921612bfd7759a67950fc6f74ffee6679c876/src/sk/maha/vypis/DirectoryPathValidation.java#L8

**Comment by mhanis2** [comment]
Upravene aby akceptovalo aj male pismeno.
