### ISSUE TITLE
Nazov triedy obvykle neobsahuje sloveso

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Vypis_adresara#3]
to je uloha metod. Tato trieda je pomenovana ako metoda. Toto nie je vhodny nazov. Je to jednoznacne validacna trieda a kedze uz ich mas dve, tak stoji za zvazenie dat ich do nejakeho spolocneho adresara validation. Alebo by som celu logiku preniesol do triedy DirectoryPathValidation. Lebo takto mas dve triedy, ktore robia nad rovnakymi datami. Potom je otazne, ci stoji za to, mat v package 1 triedu. To su vecne suboje programatorov na projekte, ci mat 1 triedu v package, ci si taky package vobec zasluzi existovat. Je to na tebe. Za chybu nebudem povazovat ani jednu z moznosti, pretoze su podla mna obidve v poriadku. Pre tento skolsky pripad by som asi zvolil nie vlastny package, v realnom projekte potom podla citatelnosti struktury projektu.

https://github.com/mhanis2/Vypis_adresara/blob/a2b921612bfd7759a67950fc6f74ffee6679c876/src/sk/maha/vypis/GetDirectoryPath.java#L6

**Comment by mhanis2** [comment]
Triedu GetDirectoryPath som odstranil a jej metody som presunul do triedy DirectoryPathValidation.
