### ISSUE TITLE
Vypisovanie struktury

### ISSUE THREAD

**Issue by MartinParak** [mhanis2/Vypis_adresara#4]
Na to, aby program pekne a prehladne vypisoval to, co ma, staci urobit dve drobne zmeny v tejto triede.

- riadok 20. Preco ked chces iba odsadit text, aby si zvyraznil, ze ide o dalsiu uroven vnorenia adresarov, tak ho hned aj odriadkujes? Robi to dost velky chaos vo vypisoch. Kazda uroven vnorenia adresara ti urobi dalsi raidok navyse. Keby si pouzil iba print namiesto println, tak to robi to, co si od toho ocakaval
- riadok 23. Vhodnejsie by bolo nepisat tam, ze ide o directory, ale vypisat ho napr. velkymi pismenami.
				
`System.out.print("\t");`
`System.out.println(oneFile.getName().toUpperCase() + ":");`

https://github.com/mhanis2/Vypis_adresara/blob/a2b921612bfd7759a67950fc6f74ffee6679c876/src/sk/maha/vypis/Listing.java#L6

**Comment by mhanis2** [comment]
Upravil som to tak, ze sa priecinok vypisuje s velkymi pismenami.
